name: nicolaj
favicon: null
layout_spectrum: 0.04476002326650308
typography_spectrum: 0.4378972580068805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#505050'
    - '#aeaeae'
    - '#7f7f7f'
  brandStrength: 1
  lightness: 0.339411475662059
  saturation: 0.21131188550834545
  rhythmicContrast: 0.6429704859202116
purpose:
  - name: null
    item: null
    url: null
